# Generated by Django 3.0 on 2020-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
